### ISSUE TITLE
oauth_callback should be sent when requesting a request token

### ISSUE THREAD

**Issue by paulosman** [joestump/python-oauth2#10]
It's currently difficult to send the oauth_callback parameter when requesting a request token (as per section 6.1.1 of the oauth 1.0a community spec: http://oauth.net/core/1.0a/#auth_step1). In order to make it work, I had to include the oauth_callback param in the 'body' of the client request:

import urllib
import oauth2 as oauth

key = 'mykey'
secret = 'mysecret'
callback_uri = 'http://mycallback/uri'

consumer = oauth.Consumer(key, secret)
client = oauth.Client(consumer)
client.set_signature(oauth.SignatureMethod_PLAINTEXT())

# get the request token
body = urllib.urlencode(dict(oauth_callback=callback_uri))
resp, content = client.request(request_token_uri, 'POST', body=body)

This feels like a hack and isn't clear from reading any of the examples. It would be much more intuitive if the caller was able to pass the callback uri as a kwarg to the client constructor or to the request method, i.e.:

client = oauth.Client(..)
...
client.request(uri, 'POST', callback=callback)

**Comment by jaitaiwan** [comment]
Closed byy #32
