### ISSUE TITLE
Need to accept new parameters once httplib2 issue 221 is resolved

### ISSUE THREAD

**Issue by jghiloni** [joestump/python-oauth2#118]
I wrote http://code.google.com/p/httplib2/issues/detail?id=221&thanks=221&ts=1344549199 it was to allow httplib2.Http to accept SSL versions for a given site. Because of a bug in openssl for Ubuntu 12.04, you can't connect to sites that only accept TLSv1 like evernote, mediafire, and the google app engine. This will require a patch for oauth2.Client as well. 

patch at https://gist.github.com/3308422

Obviously, this won't work until the httplib2 issue is resolved. Thanks for taking a look at it!

**Comment by jaitaiwan** [comment]
Not sure what this is supposed to be... @joestump ?

**Comment by jghiloni** [comment]
I suspect this is probably no longer an issue since it's 3 years old :)
