### ISSUE TITLE
setup.py install issue

### ISSUE THREAD

**Issue by jweitz** [joestump/python-oauth2#143]
Keep getting a failed install with a syntax error in line 18.  It is stating it can't find the versionfile.  Tried installing using easy_install and pip.  System is Windows 7 x64 and using Python 3.3.

Here's a copy of the pip.log file

------------------------------------------------------------
C:\Python33\Scripts\pip-script.py run on 07/01/13 19:11:07
Downloading/unpacking oauth2

  Getting page https://pypi.python.org/simple/oauth2/
  URLs to search for versions for oauth2:
  * https://pypi.python.org/simple/oauth2/
  Analyzing links from page https://pypi.python.org/simple/oauth2/
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.153.tar.gz#md5=7947445ec69aaa53acce69bbc6bbfa43 (from https://pypi.python.org/simple/oauth2/), version: 1.5.153
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.165.tar.gz#md5=d01aeced773e049397272c938ebba78c (from https://pypi.python.org/simple/oauth2/), version: 1.5.165
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.164.tar.gz#md5=4884e50db34af4a0baa4e7ab8de31236 (from https://pypi.python.org/simple/oauth2/), version: 1.5.164
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.160.tar.gz#md5=f229ee611861611ef9f0655d39eeaa71 (from https://pypi.python.org/simple/oauth2/), version: 1.5.160
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.0.6.tar.gz#md5=2440fc20687865cda0098afd60af4e28 (from https://pypi.python.org/simple/oauth2/), version: 1.0.6
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.158.tar.gz#md5=645ecb5b5caa257c202dd0e5199ca34f (from https://pypi.python.org/simple/oauth2/), version: 1.5.158
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.1.0.tar.gz#md5=ae13d1ee52f7a23770acf2899131f7fa (from https://pypi.python.org/simple/oauth2/), version: 1.1.0
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.167.tar.gz#md5=28b8b50582d619ab1f5015eee101da92 (from https://pypi.python.org/simple/oauth2/), version: 1.5.167
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.159.tar.gz#md5=02a9d1c9d93b8914e843317a054b88c2 (from https://pypi.python.org/simple/oauth2/), version: 1.5.159
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.210.tar.gz#md5=f1e296845270e35e12b7ad8c9fad65ef (from https://pypi.python.org/simple/oauth2/), version: 1.5.210
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.1.1.tar.gz#md5=b28e24bc2f6f61fce9beec52eec86d2f (from https://pypi.python.org/simple/oauth2/), version: 1.1.1
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.163.tar.gz#md5=e25a14ab1d2e3cddf03470cb4d44c5fc (from https://pypi.python.org/simple/oauth2/), version: 1.5.163
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.162.tar.gz#md5=b4a4976e2890911b1abcfa2321041973 (from https://pypi.python.org/simple/oauth2/), version: 1.5.162
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.1.3.tar.gz#md5=79ab3c0af3a6295a699f37d0c25239db (from https://pypi.python.org/simple/oauth2/), version: 1.1.3
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.150.tar.gz#md5=b11224d05ed585d78609b52d14cb91fb (from https://pypi.python.org/simple/oauth2/), version: 1.5.150
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.168.tar.gz#md5=bfe75a026287158141e9b0d69d194ed5 (from https://pypi.python.org/simple/oauth2/), version: 1.5.168
    Found link https://pypi.python.org/packages/any/o/oauth2/oauth2-1.0.6.macosx-10.6-universal.tar.gz#md5=3278190f3ca2828b88d19d6d4d484042 (from https://pypi.python.org/simple/oauth2/), version: 1.0.6.macosx-10.6-universal
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.0.9.tar.gz#md5=59b5c86c86331a60775a93f39a96bc8e (from https://pypi.python.org/simple/oauth2/), version: 1.0.9
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.0.8.tar.gz#md5=81b743950fbd6f44eb8e3f3d9f5f320b (from https://pypi.python.org/simple/oauth2/), version: 1.0.8
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.0.0.tar.gz#md5=c1c735b618cea0af6c28a4c29d235cbe (from https://pypi.python.org/simple/oauth2/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.166.tar.gz#md5=066caee006896dc0d8702a3d8e6407d7 (from https://pypi.python.org/simple/oauth2/), version: 1.5.166
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.169.tar.gz#md5=337e3e0d0c5e0233eaf096ca7ce3aa22 (from https://pypi.python.org/simple/oauth2/), version: 1.5.169
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.0.7.tar.gz#md5=8387e255a5764cb82677e5ab860db5eb (from https://pypi.python.org/simple/oauth2/), version: 1.0.7
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.155.tar.gz#md5=a974c034ced2ea8a0bb67511d6618188 (from https://pypi.python.org/simple/oauth2/), version: 1.5.155
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.2.0.tar.gz#md5=42b41a74632ccceb6094b5c232f3efec (from https://pypi.python.org/simple/oauth2/), version: 1.2.0
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.170.tar.gz#md5=5cca4f4ce2225781c2d91e19aad207f5 (from https://pypi.python.org/simple/oauth2/), version: 1.5.170
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.161.tar.gz#md5=27e384793f5e2fca181e4d75420d1978 (from https://pypi.python.org/simple/oauth2/), version: 1.5.161
    Found link https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.211.tar.gz#md5=987ad7365a70e2286bd1cebb344debbc (from https://pypi.python.org/simple/oauth2/), version: 1.5.211
  Ignoring link https://pypi.python.org/packages/any/o/oauth2/oauth2-1.0.6.macosx-10.6-universal.tar.gz#md5=3278190f3ca2828b88d19d6d4d484042 (from https://pypi.python.org/simple/oauth2/), version 1.0.6.macosx-10.6-universal is a pre-release (use --pre to allow).
  Using version 1.5.211 (newest of versions: 1.5.211, 1.5.210, 1.5.170, 1.5.169, 1.5.168, 1.5.167, 1.5.166, 1.5.165, 1.5.164, 1.5.163, 1.5.162, 1.5.161, 1.5.160, 1.5.159, 1.5.158, 1.5.155, 1.5.153, 1.5.150, 1.2.0, 1.1.3, 1.1.1, 1.1.0, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.0)
  Downloading oauth2-1.5.211.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.211.tar.gz#md5=987ad7365a70e2286bd1cebb344debbc (from https://pypi.python.org/simple/oauth2/)
  Running setup.py egg_info for package oauth2

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "c:\users\cweitz4\appdata\local\temp\pip-build-cweitz4\oauth2\setup.py", line 18

        print "unable to find version in %s" % (VERSIONFILE,)

                                           ^

    SyntaxError: invalid syntax

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\cweitz4\appdata\local\temp\pip-build-cweitz4\oauth2\setup.py", line 18

    print "unable to find version in %s" % (VERSIONFILE,)

                                       ^

SyntaxError: invalid syntax

----------------------------------------

Cleaning up...

  Removing temporary dir c:\users\cweitz4\appdata\local\temp\pip-build-cweitz4...
Command python setup.py egg_info failed with error code 1 in c:\users\cweitz4\appdata\local\temp\pip-build-cweitz4\oauth2

Exception information:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\pip-1.5.dev1-py3.3.egg\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python33\lib\site-packages\pip-1.5.dev1-py3.3.egg\pip\commands\install.py", line 235, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python33\lib\site-packages\pip-1.5.dev1-py3.3.egg\pip\req.py", line 1124, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python33\lib\site-packages\pip-1.5.dev1-py3.3.egg\pip\req.py", line 257, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python33\lib\site-packages\pip-1.5.dev1-py3.3.egg\pip\util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in c:\users\cweitz4\appdata\local\temp\pip-build-cweitz4\oauth2

**Comment by jaitaiwan** [comment]
@jweitz can you close this issue? This repo is no longer maintained. See 158

**Comment by joestump** [comment]
See #158 and the PT3K label for more. PT3K support is coming, but not official.
