### ISSUE TITLE
Parameters containing tilde characters are incorrectly escaped

### ISSUE THREAD

**Issue by ploppy** [joestump/python-oauth2#15]
oauth2.Request.get_normalized_parameters uses urllib.urlencode, which percent-encodes the tilde character (~). This conflicts with RFC 5849, section 3.6, which states that ~ must not be percent-encoded. This means that oauth2 currently generates incorrect signatures for requests whose parameters contain a tilde.

**Comment by jaitaiwan** [comment]
Closing with master containing fix. 1.9RC1 will be pushed to pypi shortly.
