### ISSUE TITLE
RSA signature method

### ISSUE THREAD

**Issue by moocher** [joestump/python-oauth2#16]
Thanks for writing this very useful library.
I could not see a SignatureMethod_RSA method included in the source, so I wrote one that uses M2Crypto. I am not sure if it will be useful for someone else, but here is the code in case it might be.

"""
A signature method class for RSA signing, for use with oauth2.
Requires M2Crypto
"""
import base64
import hashlib
import oauth2
from M2Crypto import RSA

class SignatureMethod_RSA(oauth2.SignatureMethod):
    """ RSA signature not implemented by oauth2."""
    name = "RSA-SHA1"

    def __init__(self, key_path):
        super(oauth2.SignatureMethod, self).__init__()
        self.key_path = key_path
        self.RSA = RSA.load_key(key_path)

    def signing_base(self, request):
        """Calculates the string that needs to be signed."""
        sig = (
            oauth2.escape(request.method),
            oauth2.escape(request.normalized_url),
            oauth2.escape(request.get_normalized_parameters()),
        )
        raw = '&'.join(sig)
        return raw

    def sign(self, request, consumer, token):
        """Returns the signature for the given request.
        Note: consumer and token are not used, but are there to fit in with
        call in oauth2 module.
        """
        raw = self.signing_base(request)
        digest = hashlib.sha1(raw).digest()
        signature = self.RSA.sign(digest, algo="sha1")
        encoded = base64.b64encode(signature)
        return encoded

**Comment by jaitaiwan** [comment]
This could be implemented in hmac couldn't it? cc @joestump

**Comment by joestump** [comment]
I'm honestly not sure if RSA signatures are thing people use anymore with OAuth now that OAuth 2.0 is out and forces SSL. I don't think this is the same as HMAC as that's a hashing mechanism, while this uses public/private keys for signing the signature.

**Comment by jaitaiwan** [comment]
Once again duh on my behalf. Closing this as I'm fairly certain people should be using oauth2 eventually anyway.
