### ISSUE TITLE
request with codage problem?

### ISSUE THREAD

**Issue by KunFly** [joestump/python-oauth2#166]
Hello, 

i try to use this to make a request with chinese such like:

def twitterreq(url, method, parameters):
  req = oauth.Request.from_consumer_and_token(oauth_consumer,
                                             token=oauth_token,
                                             http_method=http_method,
                                             http_url=url, 
                                             parameters=parameters)

  req.sign_request(signature_method_hmac_sha1, oauth_consumer, oauth_token)

  headers = req.to_header()

  if http_method == "POST":
    encoded_post_data = req.to_postdata()
  else:
    encoded_post_data = None    
    print req
    url = req.to_url()

  opener = urllib.OpenerDirector()
  opener.add_handler(http_handler)
  opener.add_handler(https_handler)

  response = opener.open(url, encoded_post_data)

  return response

def fetchsamples():
  url = "https://api.twitter.com/1.1/search/tweets.json?q=好的"
  parameters =  []
  response = twitterreq(url, "GET", parameters)
  for line in response:
    print line.strip()

if __name__ == '__main__':
  fetchsamples()

but i got a proble like this:

  File "C:\Python27\lib\urllib.py", line 1354, in urlencode
    l.append(k + '=' + quote_plus(str(elt)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-4: ordin
al not in range(128)

what should i do?

thank you in advance. 

fly

**Comment by jaitaiwan** [comment]
Hi @KunFly this seems to be an issue with python encoding and not this library. As such this library is no longer maintained. Can you please close your issue? Thanks

**Comment by jaitaiwan** [comment]
Hi @KunFly this repo has been given maintainers again. I believe the latest master branch has a fix for this error. I'm closing this unless you still have this issue. Thanks
