### ISSUE TITLE
Issue with installing python-oauth2

### ISSUE THREAD

**Issue by ankit481** [joestump/python-oauth2#167]
While installing the module, I received the following error message -

PS C:\Users\Dell\Downloads\python-oauth2-master\python-oauth2-master> ls

    Directory: C:\Users\Dell\Downloads\python-oauth2-master\python-oauth2-master

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        13-12-2011  09:39:06            debian
d----        13-12-2011  09:39:06            example
d----        13-12-2011  09:39:06            oauth2
d----        13-12-2011  09:39:06            tests
-----        13-12-2011  09:39:06         23 .gitignore
-----        13-12-2011  09:39:06       1071 LICENSE.txt
-----        13-12-2011  09:39:06       4042 Makefile
-----        13-12-2011  09:39:06      15198 README.md
-----        13-12-2011  09:39:06          0 setup.cfg
-a---        13-12-2011  09:39:06       1233 setup.py

PS C:\Users\Dell\Downloads\python-oauth2-master\python-oauth2-master> python .\setup.py build
Traceback (most recent call last):
  File ".\setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
PS C:\Users\Dell\Downloads\python-oauth2-master\python-oauth2-master>

Please advise on resolving the issue.

**Comment by simon-andrews** [comment]
You probably need to install [setuptools](https://bitbucket.org/pypa/setuptools).

**Comment by jaitaiwan** [comment]
Hi @ankit481, if your problem is resolved can you please close the issue? Thanks

**Comment by jaitaiwan** [comment]
@ankit481 I'm going to close this issue as its due to not having setuptools installed. Thakns
