### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Token'

### ISSUE THREAD

**Issue by navyad** [joestump/python-oauth2#169]
import oauth2 as oauth
url = "https://api.twitter.com/1.1/statuses/oembed.json"
token = oauth.Token(key=ACCESS_TOKEN, secret=ACCESS_TOKEN_SECRET)
consumer = oauth.Consumer(key=CONSUMER_KEY, secret=CONSUMER_SECRET)
................

Is anybody have clue about this one ?

**Comment by catorda** [comment]
I ran into this issue, because I installed python-oauth2 (https://pypi.python.org/pypi/python-oauth2/0.7.0) instead of the oauth2 module (https://pypi.python.org/pypi/oauth2/1.5.211). I used pip freeze to list the python packages I have installed

**Comment by jaitaiwan** [comment]
Hi, not sure if you're aware but this repo is no longer maintained. If you could please close your issue that would be a big help. Thanks.

**Comment by jaitaiwan** [comment]
Issue seems to happen when installing the wrong package.

**Comment by jaitaiwan** [comment]
@joestump Maybe we need to make this more obvious?

**Comment by joestump** [comment]
We can update the description on PyPi.

**Comment by deveshpal** [comment]
I think it still persist? Any alternatives?
