### ISSUE TITLE
Support Python Wheels

### ISSUE THREAD

**Issue by rickhanlonii** [joestump/python-oauth2#186]
From http://pythonwheels.com/, this repo is one of the 360 most-downloaded packages on PyPI and we don't have wheels support.

**Comment by jaitaiwan** [comment]
That's something I wouldn't mind having in 1.9-RC2 provided it isn't too complex to implement.

**Comment by jaitaiwan** [comment]
I've added a wheel for py2.7 rc1. Had to modify the version string to help it comply with PEP440 which I'll include in a PR potentially along side the classifiers update. I'm going to wait to see if you have comments on wheel support or if pythonwheels.com shows that we now comply.

**Comment by rickhanlonii** [comment]
Looks like we're good now, thanks @jaitaiwan! 

![](http://cl.ly/image/0E1q3E3r1801/Image%202015-08-18%20at%2011.55.43%20AM.png)

**Comment by jaitaiwan** [comment]
I'm going to leave this one open and unsolved. I don't think I can mark it as complete unless package submission is automated

**Comment by jaitaiwan** [comment]
Will close this one out and make automated wheel updates in a new ticket.
