### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by davidfstr** [joestump/python-oauth2#191]
Attempting to pip-install oauth2 gives a SyntaxError on a print statement lacking parens when in a Python 3 environment. Therefore I assume oauth2 does not support Python 3 at the moment.

Any plans to add support for Python 3 in the future?

**Comment by jaitaiwan** [comment]
Hi @davidfstr 

You're correct, although we are actively working on it. The plan is to release 1.9 soon (as soon as I get the readme finished) and then release py3k in version 2

**Comment by jaitaiwan** [comment]
Closing this thanks to the latest 1.9 release :+1: it has py3k in it!
