### ISSUE TITLE
Possible error in flow when callback are used

### ISSUE THREAD

**Issue by al3xandru** [joestump/python-oauth2#20]
While looking at the various clients/examples I got the feeling that the flow used when a callback is needed is kind of incorrect.

Basically, in the sample code the callback is submitted to the service provider once the request token must be authorized by the end user. 

According to Twitter Oauth the callback should be submitted to the service provide when obtaining the request token. This makes some sense as the server provider may decide not to confirm the callback and so the consumer will have to change the strategy used when authorizing the request token from callback to user input validation.

While I've been able to go around this issue, by including special headers and so, I think it would be worth reviewing this scenario and making sure it is correct

**Comment by jaitaiwan** [comment]
Closed by #32
