### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Consumer'

### ISSUE THREAD

**Issue by tonthon** [joestump/python-oauth2#210]
It seems the doc is not up to date, there is no Consumer class anymore in the library.

In [5]: consumer = oauth.Consumer(key=client_id, secret=client_secret)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d4e99b8dc481> in <module>()
----> 1 consumer = oauth.Consumer(key=client_id, secret=client_secret)

AttributeError: 'module' object has no attribute 'Consumer'

**Comment by markunsworth** [comment]
oh yes there is:

https://github.com/joestump/python-oauth2/blob/master/oauth2/__init__.py#L181

How are you importing oauth? Can you show more of the code?

**Comment by tonthon** [comment]
I started with the release currently available on pypi. Docs are related to the upstream version.
With the current upstream package it works.
