### ISSUE TITLE
Path in base string uri does not support matrix parameters

### ISSUE THREAD

**Issue by groodt** [joestump/python-oauth2#35]
Im trying to use python-oauth2 against Yahoo! OAuth APIs. Yahoo! makes extensive use of matrix parameters in their APIs. Example here: http://developer.yahoo.com/social/rest_api_guide/social_dir_api.html#social_dir_intro-matrix_params  Unfortunately, python-oauth2 does not seem to calculate the oauth signature correctly when there are matrix params. Matrix params are supported in the spec: in the OAuth RFC http://tools.ietf.org/html/rfc5849#section-3.4.1.2 it mentions the path should be valid according to http://tools.ietf.org/html/rfc3986#section-3.3 This section of the spec does seem to accept matrix params, and Yahoo! would hopefully not be providing non-valid OAuth APIs.

I've tracked it down to the use of urlparse.urlparse(). This is dropping the matrix params. I think we should be using urlparse.urlsplit() instead.

**Comment by joestump** [comment]
Merged in #36.
