### ISSUE TITLE
Python 2.4 (small) issue (module is callable error)

### ISSUE THREAD

**Issue by gnotaras** [joestump/python-oauth2#54]
There is an error when this module runs in python 2.4. I put a small patch inline here because github won't let me attach files:

<pre>
diff -r 89426279318c -r ea8401431426 oauth2/__init__.py
--- a/oauth2/__init__.py	Mon Feb 14 21:35:07 2011 +0200
+++ b/oauth2/__init__.py	Mon Feb 14 21:36:07 2011 +0200
@@ -471,7 +471,7 @@
             # section 4.1.1 "OAuth Consumers MUST NOT include an
             # oauth_body_hash parameter on requests with form-encoded
             # request bodies."
-            self['oauth_body_hash'] = base64.b64encode(sha(self.body).digest())
+            self['oauth_body_hash'] = base64.b64encode(sha.new(self.body).digest())
 
         if 'oauth_consumer_key' not in self:
             self['oauth_consumer_key'] = consumer.key

</pre>

**Comment by jaitaiwan** [comment]
@joestump I don't know if we want to support 2.4?

**Comment by joestump** [comment]
A valid question. 2.4 was released 11 years ago. RHEL EOL'd support for 2.4 in April of 2014 and will completely [kill it for extended support in 2017](https://mail.python.org/pipermail/python-dev/2011-December/115106.html).

**Comment by jaitaiwan** [comment]
And py3k was released 7 years ago as well. I opt for killing 2.4 support in the repo especially considering its been unmaintained for so long. What do you think @rickhanlonii?

**Comment by rickhanlonii** [comment]
I'm +1 to dropping 2.4 support.

The code in OP references the `sha` module, which was [deprecated in 2.5](https://docs.python.org/2/library/sha.html). We should replace it with `hashlib`, [which](https://docs.python.org/2/library/hashlib.html#module-hashlib) would break 2.4 anyway.

I can update the readme, which currently stops support at 2.3.

**Comment by jaitaiwan** [comment]
Sweet. Closing for #177.
