### ISSUE TITLE
Bug 'TypeError: 'module' object is not callable' in file oauth2/__init__.py

### ISSUE THREAD

**Issue by fjorgemota** [joestump/python-oauth2#55]
Hello.

I'm using the python-oauth2 with my website for login in django via twitter. And i founded this bug, in python 2.4 in the line 493. Thanks.

**Comment by jaitaiwan** [comment]
Python 2.4 is not supported with python-oauth2. Often the above error is caused by using pip to install python-oauth2 rather than just oauth2.
