### ISSUE TITLE
test_oauth.py fails to import oauth2 unless oauth2 is already installed

### ISSUE THREAD

**Issue by bassdread** [joestump/python-oauth2#61]
Running the tests without installing oauth2 fails, this appears to be a simple case of not updating the library path before doing the import. The error is below.

python-oauth2/tests$ python test_oauth.py
Traceback (most recent call last):
  File "test_oauth.py", line 29, in <module>
    import oauth2 as oauth
ImportError: No module named oauth2

**Comment by jaitaiwan** [comment]
Fixed in #62
