### ISSUE TITLE
Can't send unicode/utf-8 body with Python 2.7

### ISSUE THREAD

**Issue by kylemacfarlane** [joestump/python-oauth2#63]
The httplib in Python 2.7 has changed and tries to merge the headers and body if the body is an instance of str/unicode (lines 794-796 in 2.7's httplib.py).

For some reason \_\_init\_\_ for oauth2's Request class (lines 348-341 in \_\_init\_\_.py) converts the parameter keys to unicode and so the entire request header will always be a unicode object (unicode + str = unicode). I'm not really sure why oauth2 does this since all parameter values are converted to strings anyway (line 392).

The end result is that I can't send any unicode/utf-8 data with oauth2 and Python 2.7 because:

* Sending a utf-8 encoded string raises a UnicodeDecodeError when httplib tries to append it to the unicode header.
* Sending a unicode object raises a UnicodeDecodeError on line 493 when oauth2 tries to hash the body.
* Sending a file like object raises a TypeError on line 493 when oauth2 tries to hash the body.

**Comment by jaitaiwan** [comment]
@kylemacfarlane we've done some recently merging which has fixed a few utf8/ascii issues. Can you check and see if this is still an issue?

**Comment by kylemacfarlane** [comment]
It's been so long since I reported this issue that I can't even remember where I used this library.

**Comment by jaitaiwan** [comment]
No worries. I might just close this for now @joestump
