### ISSUE TITLE
tests package installed stupidly

### ISSUE THREAD

**Issue by djc** [joestump/python-oauth2#69]
1.5.170 installs the tests in site-packages/tests. This is obviously not a good idea: at the very least, prone to collisions with some other packages. It seems to happen because setuptools.find_packages() correctly finds the tests package and then installs it.

I think there are two viable options of resolving this:

* don't install the tests
* move the tests into the oauth2 package

I'd be happy to contribute a patch, but I don't think that would be the sticky point here.

**Comment by joestump** [comment]
We now run tests via `py.test` and use `virtualenv` locally. Additionally, we have [Travis-CI running](https://travis-ci.org/joestump/python-oauth2).

**Comment by jaitaiwan** [comment]
Specifically #173  should resolve this when merged.

**Comment by joestump** [comment]
@jaitaiwan Yeah, I think I totally missed what @djc was asking here. As you mentioned, resolved when #173 is merged.
