### ISSUE TITLE
No module named Oauth2

### ISSUE THREAD

**Issue by sebfie** [joestump/python-oauth2#74]
Hello,

I am trying to use Django Social (https://github.com/uswaretech/Django-Socialauth) and i got the error Oauth2 BUT :

When i do "import oauth2" in command line, it works, but when i use it with apache, i got the error "No module named Oauth2"

Anyone can help me?

Thank you

**Comment by joestump** [comment]
Guessing you got this figured out, but sounds like your `sys.path` needs to be updated in your Apache or related Python environment configs.
