### ISSUE TITLE
oauth_parameters_absent:scope

### ISSUE THREAD

**Issue by greggy** [joestump/python-oauth2#79]
Hello!

I want to use python-oauth2 in my project. Played like:

     In [1]: import oauth2 as oauth
     In [2]: consumer_key='dijscrape.ep.io'
     In [3]: consumer_secret='my-secret-here'
     In [4]: REQUEST_TOKEN_URL = 'https://www.google.com/accounts/OAuthGetRequestToken'
     In [5]: consumer = oauth.Consumer(consumer_key, consumer_secret)
     In [6]: client = oauth.Client(consumer)
     In [7]: r, c = client.request(REQUEST_TOKEN_URL, "GET")
     In [8]: print r
     ------> print(r)
    {'status': '400', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'expires': 'Tue, 26 Jul 2011 13:38:13 GMT', 'server': 'GSE', 'cache-control': 'private, max-age=0', 'date': 'Tue, 26 Jul 2011 13:38:13 GMT', 'content-type': 'text/plain; charset=UTF-8'}

    In [9]: print c
    ------> print(c)
    parameter_absent
    oauth_parameters_absent:scope

What it can be?

**Comment by joestump** [comment]
@greggy I'm guessing you got this one figured out, but some providers require you to tell them what OAuth scope you'd like to authorize a token for.
