### ISSUE TITLE
Python 2.4 compatibility problem with urlparse

### ISSUE THREAD

**Issue by eserra** [joestump/python-oauth2#8]
I have setup a simple Client with v1.1.3 as in your Twitter example but I get the following error

File "/var/lib/zope3/instance/satisfly/lib/python/satisfly/browser/connections.py", line 272, in __call__
  print client.request(request_token_url, "GET")
File "build/bdist.linux-x86_64/egg/oauth2/__init__.py", line 622, in request
  
File "build/bdist.linux-x86_64/egg/oauth2/__init__.py", line 317, in to_url

I investigated a bit and I noticed that you are expecting urlparse.urlparse returning an object with a query property:

    def to_url(self):
        """Serialize as a URL for a GET request."""
        base_url = urlparse.urlparse(self.url)
        query = parse_qs(base_url.query)
        [...]

But my version returns a 6-tuple

Tnx for your help

Regards

**Comment by jaitaiwan** [comment]
Refer to #54 question about py24 support.

**Comment by rickhanlonii** [comment]
Sorry @eserra, Python 2.4 is no longer supported. See #54.
