### ISSUE TITLE
Client class does not use super()

### ISSUE THREAD

**Issue by portante** [joestump/python-oauth2#81]
See http://rhettinger.wordpress.com/2011/05/26/super-considered-super/.

If one would like to create a new class composed with Client, the method resolution order will still be fixed by the current implementation because it does not use super().

**Comment by joestump** [comment]
It does now. Merged into `master` in an unrelated PR.

**Comment by jaitaiwan** [comment]
Sorry @joestump I know I'm being a pain. Can you please reference the commit?

**Comment by joestump** [comment]
@jaitaiwan you're not being a pain at all. I should have done this the first time around. It was merged into master in commit d0d9a2d2fa3b7458d18ec5a8c7cd1c5e9b02bebd when #159 was merged.

**Comment by jaitaiwan** [comment]
Thanks!
