### ISSUE TITLE
oauth 2.0?

### ISSUE THREAD

**Issue by eykd** [joestump/python-oauth2#83]
It's my understanding that python-oauth2 is actually an implementation of OAuth 1.0. With the OAuth 2.0 final spec imminent, this is going to get really confusing for anyone trying to use the new, non-backwards-compatible spec, especially as there doesn't seem to be a complete OAuth 2.0 implementation in python yet. Is there anything you guys can do to mitigate this?

**Comment by JasonThomasData** [comment]
Is this resolved yet? An issue from 2011 is not resolved? OK

**Comment by intellix** [comment]
why is there a 2 in the repository name `python-oauth2` if it has nothing to do with 2?

**Comment by rickhanlonii** [comment]
@intellix it's the second python-oauth library (and was created before there was an oauth 2)

Closing since the doc update in https://github.com/joestump/python-oauth2/pull/202 clarifies this
