### ISSUE TITLE
installs a tests module into site-packages

### ISSUE THREAD

**Issue by schwehr** [joestump/python-oauth2#87]
oauth2 installs a site-packages/tests module.  This surely should not be installed.  Mac osx 10.7.1 with fink providing python 2.7.

-kurt

    /sw/bin/python2.7 setup.py install --root /sw/src/fink.build/root-oauth2-py27-1.5.170-1
    ....
    opying build/lib/oauth2/clients/smtp.py -> /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/clients
    creating /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests
    copying build/lib/tests/__init__.py -> /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests
    copying build/lib/tests/test_oauth.py -> /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/__init__.py to __init__.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/_version.py to _version.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/clients/__init__.py to __init__.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/clients/imap.py to imap.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2/clients/smtp.py to smtp.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests/__init__.py to __init__.pyc
    byte-compiling /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests/test_oauth.py to test_oauth.pyc
    running install_egg_info
    running egg_info
    writing requirements to oauth2.egg-info/requires.txt
    writing oauth2.egg-info/PKG-INFO
    writing top-level names to oauth2.egg-info/top_level.txt
    writing dependency_links to oauth2.egg-info/dependency_links.txt
    reading manifest file 'oauth2.egg-info/SOURCES.txt'
    writing manifest file 'oauth2.egg-info/SOURCES.txt'
    Copying oauth2.egg-info to /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/oauth2-1.5.170-py2.7.egg-info
    running install_scripts
    ls -l /sw/src/fink.build/root-oauth2-py27-1.5.170-1/sw/lib/python2.7/site-packages/tests
    total 224
    -rw-r--r--  1 root  admin      0 May  2 19:48 __init__.py
    -rw-r--r--  1 root  admin    136 Aug 25 22:10 __init__.pyc
    -rw-r--r--  1 root  admin  53269 May  2 19:48 test_oauth.py
    -rw-r--r--  1 root  admin  51229 Aug 25 22:10 test_oauth.pyc

**Comment by joestump** [comment]
Definitely not good.

**Comment by thehcma** [comment]
Is it possible to release a version (on PyPi) with this fix?
