### ISSUE TITLE
docs/faq update - oauth2 implementation?

### ISSUE THREAD

**Issue by aljosa** [joestump/python-oauth2#92]
i didn't find any other way to ask this so i'm posting it as an issue.
are there any plans to implement oauth2 spec or is there a general consensus that oauth v1, as implemented now, is good enough?

would appreciate any info since i'm planning to use python-oauth2 on a project but can't decide if i should look for v2 implementation or just use this one.
and just to be clear, i'm talking about server implementation.

**Comment by jaitaiwan** [comment]
Oauth2 support scheduled for 2.0. PR's are already in place to bring this functionality ASAP. #83 #48 #6 #170

**Comment by mathiasconradt** [comment]
> Oauth2 support scheduled for 2.0. PR's are already in place to bring this functionality ASAP. #83 #48 #6 #170

That was 4 years ago, any planned schedule when/if this will happen at all? I also came across this lib by searching for oauth2, found the module name quite confusing as well.

**Comment by jaitaiwan** [comment]
The project is most assuredly dead and the project owner is no-where to be
found. I haven't been able to raise him on skype or get comments here.

**Comment by thackerc** [comment]
@jaitaiwan Thanks for the update.
